#COM ports for pump and stage:
pump_port: COM3
stage_port: COM4

#Pump settings:
pump_type: bartels #Can be 'CPP' or 'bartels'
bartels_freq: 150
bartels_voltage: 150
CPP_speed: 500 #1-999

#Well plate setup, coordinates in mm compared to A1 well:
well_plate:
    bottom_right:
      x: 99
      y: 63
    top_left:
      x: 0
      y: 0
    columns: 12
    rows: 8
    well_spacing: 9     # Center to center distance of wells [mm]
    z_base: -39         # Depth probe goes into well from zero position in mm.

#Custom positions outside of well plate, coordinates in mm compared to A1 position.
positions:
    SSC:
      x: 20
      y: 101
      z: -39
    strip:
      x: 20
      y: 119
      z: -39
    wash:
      x: 20
      y: 136
      z: -39

#The sequences to follow. 
# Each sequence is defined by a number of cycles for that sequence (n_cycles), a first and a last well.
# n_cycles is either number of cycles or 'all' to calculate automatically.
# first_well and last_well of the sequence can be set to 'null' if there are no wells in the sequence (or simply omitted), or the well identifyer (e.g. B3).
# Note first_well and last_well need to be set if n_cycles is 'all'.
#Possible actions and parameters are within each sequence are:
# - probe: 'wp' (for the next well in the well plate) or a custom position named precisely as listed under 'positions' above.
# - pump: time for pumping in seconds
# - pause: pause/wait time in seconds
# - image: 1, sets the status to "image" and waits for the status to change to "robot" again before proceeding.

sequences:
#    seq_A:
#        n_cycles: 1
#        sequence:
#            - probe: strip
#            - pause: 1
#            - pump: 6
#            - pause: 1
#            - probe: wash
#            - pause: 1
#            - pump: 10
#            - pause: 12
#            - pump: 6
#            - pause: 1
#            - probe: SSC
#            - pause: 1
#            - pump: 4
#            - pause: 3
#            - image: 1
    seq_B:
        n_cycles: all
        first_well: A1
        last_well: A3
        sequence:
            - probe: wp
            - pause: 1
            - pump: 4
            - pause: 1
            - probe: wash
            - pause: 1
            - pump: 10
            - pause: 12
            - pump: 6
            - pause: 3
            - probe: SSC
            - pause: 1
            - pump: 4
            - pause: 3
#            - image: 1
            - probe: strip
            - pause: 1
            - pump: 6
            - pause: 1
            - probe: wash
            - pause: 1
            - pump: 3
            - pause: 12
            - pump: 6
            - pause: 1
    seq_C:
        n_cycles: 1
        sequence:
            - probe: strip
            - pause: 1
            - pump: 6
            - pause: 1
            - probe: wash
            - pause: 1
            - pump: 10
            - pause: 12
            - pump: 6
            - pause: 1